<?php

namespace ContainerTqWEqEh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5XYYlTtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5XYYlTt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5XYYlTt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'books' => ['privates', 'App\\Repository\\BooksRepository', 'getBooksRepositoryService', true],
        ], [
            'books' => 'App\\Repository\\BooksRepository',
        ]);
    }
}
